/*
 * This source file was generated by the Gradle 'init' task
 */
package io.akshayraj;

import io.akshayraj.App;
import org.junit.Test;
import org.springframework.boot.test.context.SpringBootTest;

import static org.junit.Assert.*;

@SpringBootTest
public class AppTest {

    @Test
    public void contextLoads() {

    }

}
