services:
  clickhouse:
    image: clickhouse/clickhouse-server
    ports:
      - "9000:9000"
      - "8000:8123"
      # No need to expose 8123 publicly since proxy will handle it
    networks:
      - clickhouse-net
    environment:
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=test123
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - clickhouse-config:/etc/clickhouse-server

  jwt-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    image: openresty/openresty:alpine
    ports:
      - "8123:8123"
    networks:
      - clickhouse-net
    environment:
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=test123
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    volumes:
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./public_key.pem:/etc/public_key.pem
    depends_on:
      - clickhouse
    restart: unless-stopped

volumes:
  clickhouse-data:
  clickhouse-config:

networks:
  clickhouse-net:
    driver: bridge